included:
  - Cimon
  - Core
  - App
  - Domain
  - Shared
  - BitriseAPI
  - TravisCIAPI
  - CircleCIAPI
excluded:
  - CimonTests
  - AppTests
  - DomainTests
  - SharedTests
  - Pods
  - Carthage
disabled_rules:
  - file_length
  - line_length
  - function_body_length
  - type_name
  - variable_name
  - nesting
