name: Cimon
options:
  minimumXcodeGenVersion: "2.13.0"
  bundleIdPrefix: "com.bivre"
  deploymentTarget:
    iOS: "13.0"
  indentWidth: 4
  tabWidth: 4
configs:
  Debug: debug
  Staging: release
  Release: release
settings:
  SWIFT_VERSION: "5.1"
  DEVELOPMENT_TEAM: "PS98BD6732"
  CODE_SIGN_STYLE: "Automatic"
  TARGETED_DEVICE_FAMILY: "1,2"
  SUPPORTS_MACCATALYST: true
targets:
  Common:
    type: framework
    platform: iOS
    sources:
      - path: Common
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.common"
  TravisCIAPI:
    type: framework
    platform: iOS
    sources:
      - path: TravisCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.travisci-api"
    dependencies:
      - carthage: Mocha
  CircleCIAPI:
    type: framework
    platform: iOS
    sources:
      - path: CircleCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.circleci-api"
    dependencies:
      - carthage: Mocha
  BitriseAPI:
    type: framework
    platform: iOS
    sources:
      - path: BitriseAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.bitrise-api"
    dependencies:
      - carthage: Mocha
  Domain:
    type: framework
    platform: iOS
    sources:
      - path: Domain
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.domain"
    dependencies:
      - target: TravisCIAPI
      - target: CircleCIAPI
      - target: BitriseAPI
      - target: Common
      - carthage: Mocha
    scheme:
      testTargets:
        - DomainTests
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DomainTests
    dependencies:
      - target: Domain
      - target: Cimon
  Core:
    type: framework
    platform: iOS
    sources:
      - path: Core
      - path: Core/Sources/Generated/Assets.swift
        optional: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.core"
    dependencies:
      - target: Common
      - target: Domain
    preBuildScripts:
      - name: "[SwiftGen] Run Script"
        script: "swiftgen config run --config Core/swiftgen.yml"
  TravisCI:
    type: framework
    platform: iOS
    sources:
      - path: TravisCI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.travisci"
    dependencies:
      - target: TravisCIAPI
      - target: Common
      - target: Domain
      - target: Core
      - carthage: Mocha
  CircleCI:
    type: framework
    platform: iOS
    sources:
      - path: CircleCI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.circleci"
    dependencies:
      - target: CircleCIAPI
      - target: Common
      - target: Domain
      - target: Core
      - carthage: Mocha
  Bitrise:
    type: framework
    platform: iOS
    sources:
      - path: Bitrise
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.bitrise"
    dependencies:
      - target: BitriseAPI
      - target: Common
      - target: Domain
      - target: Core
      - carthage: Mocha
  Cimon:
    type: application
    platform: iOS
    sources:
      - path: Cimon
      - path: Cimon/Sources/Generated/Assets.swift
        optional: true
      - path: GoogleService-Info.plist
    settings:
      base:
        CODE_SIGN_STYLE: "Manual"
        PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "match Development com.bivre.cimon"
        Staging:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc com.bivre.cimon"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.bivre.cimon"
    dependencies:
      - target: TravisCIAPI
      - target: CircleCIAPI
      - target: BitriseAPI
      - target: Common
      - target: Domain
      - target: Core
      - target: TravisCI
      - target: CircleCI
      - target: Bitrise
      - package: Nuke
      - package: Pipeline
      - carthage: Mocha
      - carthage: Reachability
    preBuildScripts:
      - name: "[SwiftGen] Run Script"
        script: "swiftgen config run --config Cimon/swiftgen.yml"
      - name: "[SwiftLint] Run Script"
        script: "swiftlint"
    postBuildScripts:
      - name: "[Crashlytics] Run Script"
        script: "${PODS_ROOT}/Fabric/run"
        inputFiles:
          - "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
    scheme:
      testTargets:
        - DomainTests
        - CimonTests
  CimonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CimonTests
    dependencies:
      - target: Cimon
packages:
  Nuke:
    url: https://github.com/kean/Nuke
    from: 8.4.0
  Pipeline:
    url: https://github.com/yuta24/Pipeline
    branch: master
