name: Cimon
options:
  minimumXcodeGenVersion: "2.16.0"
  bundleIdPrefix: "com.bivre"
  deploymentTarget:
    iOS: "14.0"
  indentWidth: 4
  tabWidth: 4
configs:
  Debug: debug
  Staging: release
  Release: release
settings:
  SWIFT_VERSION: "5.3"
  DEVELOPMENT_TEAM: "PS98BD6732"
  CODE_SIGN_STYLE: "Automatic"
  TARGETED_DEVICE_FAMILY: "1,2"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.6.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.0.0
  FetchImage:
    url: https://github.com/kean/FetchImage
    from: 0.2.0
  Mocha:
    url: https://github.com/yuta24/Mocha.git
    branch: "master"
  Tagged:
    url: https://github.com/pointfreeco/swift-tagged.git
    from: 0.5.0
  Mocker:
    url: https://github.com/WeTransfer/Mocker.git
    from: 2.1.0
targets:
  Litey:
    type: framework
    platform: iOS
    sources:
      - path: Litey
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.litey"
  LiteyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LiteyTests
    dependencies:
      - target: Litey
      - target: Cimon
  Common:
    type: framework
    platform: iOS
    sources:
      - path: Common
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.common"
  APICore:
    type: framework
    platform: iOS
    sources:
      - path: APICore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.api-core"
    dependencies:
      - package: Mocha
  APICoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: APICoreTests
    dependencies:
      - target: APICore
      - target: Cimon
      - package: Mocker
  TravisCIAPI:
    type: framework
    platform: iOS
    sources:
      - path: TravisCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.travisci-api"
    dependencies:
      - target: APICore
  CircleCIAPI:
    type: framework
    platform: iOS
    sources:
      - path: CircleCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.circleci-api"
    dependencies:
      - target: APICore
  BitriseAPI:
    type: framework
    platform: iOS
    sources:
      - path: BitriseAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.bitrise-api"
    dependencies:
      - target: APICore
  GitHubAPI:
    type: framework
    platform: iOS
    sources:
      - path: GitHubAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.github-api"
    dependencies:
      - target: APICore
  Domain:
    type: framework
    platform: iOS
    sources:
      - path: Domain
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.domain"
    dependencies:
      - target: TravisCIAPI
      - target: CircleCIAPI
      - target: BitriseAPI
      - target: Common
      - package: Tagged
    scheme:
      testTargets:
        - DomainTests
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DomainTests
    dependencies:
      - target: Domain
      - target: Cimon
  Core:
    type: framework
    platform: iOS
    sources:
      - path: Core
      - path: Core/Sources/Generated/Assets.swift
        optional: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon.core"
    dependencies:
      - target: Common
      - target: Domain
      - package: ComposableArchitecture
      - package: KeychainAccess
    preBuildScripts:
      - name: "[SwiftGen] Run Script"
        script: "swiftgen config run --config Core/swiftgen.yml"
  Cimon:
    type: application
    platform: iOS
    sources:
      - path: Cimon
      - path: Cimon/Sources/Generated/Assets.swift
        optional: true
      - path: GoogleService-Info.plist
    settings:
      base:
        CODE_SIGN_STYLE: "Manual"
        PRODUCT_BUNDLE_IDENTIFIER: "com.bivre.cimon"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "match Development com.bivre.cimon"
        Staging:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc com.bivre.cimon"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.bivre.cimon"
    dependencies:
      - target: TravisCIAPI
      - target: CircleCIAPI
      - target: BitriseAPI
      - target: Common
      - target: APICore
      - target: Domain
      - target: Core
      - package: FetchImage
    preBuildScripts:
      - name: "[SwiftGen] Run Script"
        script: "swiftgen config run --config Cimon/swiftgen.yml"
      - name: "[SwiftLint] Run Script"
        script: "swiftlint"
    postBuildScripts:
      - name: "[Crashlytics] Run Script"
        script: "${PODS_ROOT}/Fabric/run"
        inputFiles:
          - "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
    scheme:
      testTargets:
        - APICoreTests
        - DomainTests
        - CimonTests
  CimonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CimonTests
    dependencies:
      - target: Cimon
