main_target: &main_target Cimon

name: *main_target
options:
  minimumXcodeGenVersion: 2.5.0
  bundleIdPrefix: com.bivre
  deploymentTarget:
    iOS: "11.0"
settings:
  DEVELOPMENT_TEAM: PS98BD6732
  CODE_SIGN_STYLE: Automatic
targets:
  Cimon:
    type: application
    platform: iOS
    sources:
      - Cimon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon
    dependencies:
      - target: Shared
      - target: Domain
      - target: App
      - carthage: APIKit
    prebuildScripts:
    #   - name: "[SwiftGen] Run Script"
    #     script: |
    #       ${PODS_ROOT}/SwiftGen/bin/swiftgen
      - name: "[SwiftLint] Run Script"
        script: |
          if which ${PODS_ROOT}/SwiftLint/swiftlint >/dev/null; then
            ${PODS_ROOT}/SwiftLint/swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    scheme:
      testTargets:
        - CimonTests
        - SharedTests
        - DomainTests
        - AppTests
  CimonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CimonTests
    dependencies:
      - target: *main_target
  Shared:
    type: framework
    platform: iOS
    sources:
      - Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.shared
    scheme:
      testTargets:
        - SharedTests
  SharedTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SharedTests
    dependencies:
      - target: *main_target
      - target: Shared
  Domain:
    type: framework
    platform: iOS
    sources:
      - Domain
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.domain
    scheme:
      testTargets:
        - DomainTests
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DomainTests
    dependencies:
      - target: *main_target
      - target: Domain
  App:
    type: framework
    platform: iOS
    sources:
      - App
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.app
    dependencies:
      - carthage: APIKit
    scheme:
      testTargets:
        - AppTests
  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AppTests
    dependencies:
      - target: *main_target
      - target: App
  BitriseAPI:
    type: framework
    platform: iOS
    sources:
      - BitriseAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.bitrise
    dependencies:
      - carthage: APIKit
  CircleCIAPI:
    type: framework
    platform: iOS
    sources:
      - CircleCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.circleci
    dependencies:
      - carthage: APIKit
  TravisCIAPI:
    type: framework
    platform: iOS
    sources:
      - TravisCIAPI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bivre.cimon.travisci
    dependencies:
      - carthage: APIKit
