default_platform(:ios)

platform :ios do
  desc "証明書＆プロビジョニングプロファイルの取得"
  lane :fetch_certificates do
    sync_code_signing(type: "development")
    sync_code_signing(type: "adhoc")
    sync_code_signing(type: "appstore")
  end

  desc "ベータアプリのビルド"
  lane :build_beta do
    sync_code_signing(type: "adhoc")
    build_ios_app(skip_package_ipa: true, export_method: "ad-hoc")
  end

  desc "ベータアプリの生成"
  lane :generate_beta do
    sync_code_signing(type: "adhoc")
    build_ios_app(export_method: "ad-hoc")
  end

  desc "自動テストの実行"
  lane :run_auto_tests do
    run_tests(workspace: "Cimon.xcworkspace", scheme: "Cimon", devices: ["iPhone Xs"])
  end
end
