default_platform(:ios)

platform :ios do
  desc "証明書＆プロビジョニングプロファイルの取得"
  lane :fetch_certificates do
    sync_code_signing(type: "development")
    sync_code_signing(type: "adhoc")
    sync_code_signing(type: "appstore")
  end

  desc "Description of what the lane does"
  lane :run_app_tests do
    run_tests(workspace: "Cimon.xcworkspace", scheme: "Cimon", devices: ["iPhone Xs"])
  end
end
