default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :run_app_tests do
    run_tests(workspace: "Cimon.xcworkspace", scheme: "Cimon", devices: ["iPhone Xs"])
  end
end
